//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIFORMOBILEAPPWORKING.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_BaoCaoHinhAnh
    {
        public string BCHA_ID { get; set; }
        public string Shop_id { get; set; }
        public string Us_id { get; set; }
        public Nullable<System.DateTime> BCHA_Time { get; set; }
        public Nullable<System.DateTime> BCHA_SyncFlag { get; set; }
        public Nullable<System.DateTime> BCHA_DeleteFlag { get; set; }
        public string Bigplan_id { get; set; }
    }
}
