//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIFORMOBILEAPPWORKING.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Dondathang
    {
        public string DDH_ID { get; set; }
        public string Us_id { get; set; }
        public string Shop_id { get; set; }
        public Nullable<System.DateTime> DDH_time { get; set; }
        public Nullable<System.DateTime> DDH_Syncflag { get; set; }
        public Nullable<System.DateTime> DDH_DeleteFlag { get; set; }
    }
}
