//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIFORMOBILEAPPWORKING.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_KHtiepcan
    {
        public string KHTC_ID { get; set; }
        public string Bigplan_id { get; set; }
        public Nullable<int> KHTC_TC { get; set; }
        public Nullable<int> KHTC_TCTC { get; set; }
        public Nullable<System.DateTime> KHTC_Datereport { get; set; }
        public Nullable<System.DateTime> KHTC_SyncFlag { get; set; }
        public Nullable<System.DateTime> KHTC_DeleteFlag { get; set; }
        public Nullable<int> KHTC_Doithu { get; set; }
    }
}
