//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIFORMOBILEAPPWORKING.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_HsSms
    {
        public string HSsms_ID { get; set; }
        public string Bill_id { get; set; }
        public string HSsms_OTP { get; set; }
        public string HSsms_OTPConfirm { get; set; }
        public Nullable<System.DateTime> HSsms_Time { get; set; }
        public string HSsms_Status { get; set; }
        public string HSsms_Code { get; set; }
        public string HSsms_Phone { get; set; }
        public Nullable<System.DateTime> HSsms_SyncFlag { get; set; }
        public Nullable<System.DateTime> HSsms_DeleteFlag { get; set; }
    }
}
