//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIFORMOBILEAPPWORKING.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_doithucanhtranh
    {
        public string dt_id { get; set; }
        public string US_ID { get; set; }
        public string Shop_id { get; set; }
        public string dt_keyacc { get; set; }
        public string dt_cty { get; set; }
        public string dt_fortmat { get; set; }
        public string dt_brand { get; set; }
        public string dt_variant { get; set; }
        public string dt_crmrange { get; set; }
        public string dt_ffrange { get; set; }
        public string dt_ltnrange { get; set; }
        public string dt_noidung { get; set; }
        public string dt_OnPostOffPost { get; set; }
        public Nullable<int> dt_giagoc { get; set; }
        public Nullable<int> dt_giakm { get; set; }
        public string dt_hangtang { get; set; }
        public Nullable<int> dt_giahangtang { get; set; }
        public string dt_post { get; set; }
        public string dt_tenpost { get; set; }
        public Nullable<System.DateTime> dt_thoigianbd { get; set; }
        public Nullable<System.DateTime> dt_thoigiankt { get; set; }
        public Nullable<int> dt_nam { get; set; }
        public string dt_type { get; set; }
        public Nullable<System.DateTime> dt_SyncFlag { get; set; }
        public Nullable<System.DateTime> dt_DeleteFlag { get; set; }
    }
}
