//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIFORMOBILEAPPWORKING.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_banhang
    {
        public string Us_id { get; set; }
        public string Us_name { get; set; }
        public string Us_username { get; set; }
        public string Us_password { get; set; }
        public string Us_Role { get; set; }
        public string Us_SupGroup { get; set; }
        public string Us_text1 { get; set; }
        public string Us_text2 { get; set; }
        public string Us_text3 { get; set; }
        public string Us_text4 { get; set; }
        public string Us_text5 { get; set; }
        public string Us_text6 { get; set; }
        public string Us_text7 { get; set; }
        public Nullable<double> Us_float1 { get; set; }
        public Nullable<double> Us_float2 { get; set; }
        public Nullable<double> Us_float3 { get; set; }
        public Nullable<double> Us_float4 { get; set; }
        public Nullable<System.DateTime> Us_datetime1 { get; set; }
        public Nullable<System.DateTime> Us_datetime2 { get; set; }
        public Nullable<System.DateTime> Us_datetime3 { get; set; }
        public Nullable<System.DateTime> Us_datetime4 { get; set; }
        public Nullable<System.DateTime> Us_datetime5 { get; set; }
        public Nullable<bool> Us_bit { get; set; }
        public Nullable<System.DateTime> Us_deleteflag { get; set; }
        public Nullable<System.DateTime> Us_SyncFlag { get; set; }
        public string US_TypeKho { get; set; }
        public string Shop_id { get; set; }
        public string Shop_name { get; set; }
        public string Shop_detail { get; set; }
        public string Shop_npp { get; set; }
        public string Shop_nppcode { get; set; }
        public string Shop_Ngcode { get; set; }
        public string Shop_LoaiCHCurrent { get; set; }
        public string Shop_LoaiCHFuture { get; set; }
        public Nullable<double> Shop_latidue { get; set; }
        public Nullable<double> Shop_Longtidue { get; set; }
        public string Shop_phone { get; set; }
        public string Shop_Sup { get; set; }
        public string Shop_GroupPrice { get; set; }
        public string Shop_text2 { get; set; }
        public string Shop_text3 { get; set; }
        public string Shop_text4 { get; set; }
        public Nullable<double> Shop_float1 { get; set; }
        public Nullable<double> Shop_float2 { get; set; }
        public Nullable<double> Shop_float3 { get; set; }
        public Nullable<double> Shop_float4 { get; set; }
        public Nullable<bool> Shop_bit { get; set; }
        public Nullable<System.DateTime> Shop_datetime1 { get; set; }
        public Nullable<System.DateTime> Shop_datetime2 { get; set; }
        public Nullable<System.DateTime> Shop_datetime3 { get; set; }
        public Nullable<System.DateTime> Shop_datetime4 { get; set; }
        public Nullable<System.DateTime> Shop_deleteflag { get; set; }
        public Nullable<System.DateTime> Shop_SyncFlag { get; set; }
        public double sku_barcode { get; set; }
        public string sku_name { get; set; }
        public string sku_detail { get; set; }
        public string sku_txtname { get; set; }
        public Nullable<double> sku_txtPrice { get; set; }
        public string Target_Group { get; set; }
        public string sku_text1 { get; set; }
        public string sku_text2 { get; set; }
        public string sku_text3 { get; set; }
        public string sku_text4 { get; set; }
        public string sku_text5 { get; set; }
        public Nullable<double> sku_float1 { get; set; }
        public Nullable<double> sku_float2 { get; set; }
        public Nullable<double> sku_float3 { get; set; }
        public Nullable<double> sku_float4 { get; set; }
        public Nullable<double> sku_float5 { get; set; }
        public Nullable<double> sku_float6 { get; set; }
        public Nullable<System.DateTime> sku_datetime1 { get; set; }
        public Nullable<System.DateTime> sku_datetime2 { get; set; }
        public Nullable<System.DateTime> sku_datetime3 { get; set; }
        public Nullable<System.DateTime> sku_datetime4 { get; set; }
        public Nullable<bool> sku_bit { get; set; }
        public Nullable<System.DateTime> sku_deleteflag { get; set; }
        public Nullable<System.DateTime> sku_SyncFlag { get; set; }
        public Nullable<System.DateTime> Bill_date { get; set; }
        public Nullable<System.DateTime> Bill_deleteFlag { get; set; }
        public string Bill_id { get; set; }
        public string Bill_ImageKH { get; set; }
        public string Bill_SDTKH { get; set; }
        public Nullable<System.DateTime> Bill_SyncFlag { get; set; }
        public string Bill_TenKH { get; set; }
        public Nullable<System.DateTime> BillDetail_deleteFlag { get; set; }
        public Nullable<double> BillDetail_dongia { get; set; }
        public Nullable<int> BillDetail_soluong { get; set; }
        public Nullable<System.DateTime> BillDetail_SyncFlag { get; set; }
    }
}
