//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBREPORTMOBILEAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_billDetail
    {
        public string Bill_id { get; set; }
        public double sku_barcode { get; set; }
        public Nullable<int> BillDetail_soluong { get; set; }
        public Nullable<double> BillDetail_dongia { get; set; }
        public Nullable<System.DateTime> BillDetail_deleteFlag { get; set; }
        public Nullable<System.DateTime> BillDetail_SyncFlag { get; set; }
        public string Bigplan_id { get; set; }
    }
}
