//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBREPORTMOBILEAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DanhMucQuaTang
    {
        public double DMQT_Barcode { get; set; }
        public string DMQT_Name { get; set; }
        public string DMQT_Detail { get; set; }
        public Nullable<bool> DMQT_Status { get; set; }
        public Nullable<System.DateTime> DMQT_SyncFlag { get; set; }
        public Nullable<System.DateTime> DMQT_DeleteFlag { get; set; }
    }
}
