//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBREPORTMOBILEAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_KhoDoi
    {
        public string KD_ID { get; set; }
        public string KD_Name { get; set; }
        public string KD_Adress { get; set; }
        public string KD_Phone { get; set; }
        public string KD_TenNguoiGiuKho { get; set; }
        public string KD_UserQL { get; set; }
        public string KD_Type { get; set; }
        public Nullable<System.DateTime> KD_SyncFlag { get; set; }
        public Nullable<System.DateTime> KD_DeleteFlag { get; set; }
    }
}
