//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBREPORTMOBILEAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_KHOQUA
    {
        public string KV_ID { get; set; }
        public string KV_Name { get; set; }
        public string KV_Adress { get; set; }
        public string KV_Phone { get; set; }
        public string KV_TenNguoiGiuKho { get; set; }
        public string KV_UserQL { get; set; }
        public string KV_Type { get; set; }
        public Nullable<System.DateTime> KV_SyncFlag { get; set; }
        public Nullable<System.DateTime> KV_DeleteFlag { get; set; }
        public string KV_TypeKhoChuyen { get; set; }
        public string KV_TypeKhoNhan { get; set; }
    }
}
