//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBREPORTMOBILEAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_DonNhapHang
    {
        public string DNH_ID { get; set; }
        public string US_ID { get; set; }
        public string Shop_id { get; set; }
        public string DNH_Image { get; set; }
        public string DNH_ImagePublish { get; set; }
        public Nullable<System.DateTime> DNH_Date { get; set; }
        public Nullable<System.DateTime> DNH_SyncFlag { get; set; }
        public Nullable<System.DateTime> DNH_DeleteFlag { get; set; }
    }
}
