//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBREPORTMOBILEAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_KhoChiNhanh
    {
        public string KCN_ID { get; set; }
        public string KCN_Name { get; set; }
        public string KCN_Adress { get; set; }
        public string KCN_Phone { get; set; }
        public string KCN_TenNguoiGiuKho { get; set; }
        public string KCN_UserQL { get; set; }
        public string KCN_Type { get; set; }
        public Nullable<System.DateTime> KCN_SyncFlag { get; set; }
        public Nullable<System.DateTime> KCN_DeleteFlag { get; set; }
    }
}
