//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBREPORTMOBILEAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SupCheckIn
    {
        public string SupCheckIn_id { get; set; }
        public string SupBigPlan_id { get; set; }
        public System.DateTime SupCheckIn_date { get; set; }
        public Nullable<double> SupCheckIn_Latidue { get; set; }
        public Nullable<double> SupCheckIn_Longtidue { get; set; }
        public string SupCheckIn_ImageCI { get; set; }
        public string SupCheckIn_ImageCO { get; set; }
        public Nullable<int> SupCheckIn_AdminAccept { get; set; }
        public string SupCheckIn_AdminNote { get; set; }
        public Nullable<System.DateTime> SupCheckIn_TimeCI { get; set; }
        public Nullable<System.DateTime> SupCheckIn_TimeCO { get; set; }
        public Nullable<double> SupCheckIn_Count { get; set; }
        public Nullable<System.DateTime> SupCheckIn_DeleteFlag { get; set; }
        public Nullable<System.DateTime> SupCheckIn_SyncFlag { get; set; }
    }
}
