//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBREPORTMOBILEAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ChitietSupChamDiem
    {
        public string ChitietSupChamDiem_ID { get; set; }
        public string SupChamDiem_id { get; set; }
        public string TieuChiCD_id { get; set; }
        public Nullable<int> ChitietSupChamDiem_value { get; set; }
        public Nullable<System.DateTime> ChitietSupChamDiem_DeleteFlag { get; set; }
        public Nullable<System.DateTime> ChitietSupChamDiem_SyncFlag { get; set; }
    }
}
