//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBREPORTMOBILEAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_ImageDonNhapHang
    {
        public string IDNH_ID { get; set; }
        public string DNH_ID { get; set; }
        public string IDNH_Image { get; set; }
        public string IDNH_ImagePublish { get; set; }
        public string IDNH_Note { get; set; }
        public Nullable<System.DateTime> IDNH_SyncFlag { get; set; }
        public Nullable<System.DateTime> IDNH_DeleteFlag { get; set; }
    }
}
