//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBREPORTMOBILEAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_chucnangphu
    {
        public string CNP_ID { get; set; }
        public string CNP_NAME { get; set; }
        public string CNP_Detail { get; set; }
        public Nullable<double> CNP_value { get; set; }
        public Nullable<bool> CNP_Status { get; set; }
        public Nullable<System.DateTime> CNP_SyncFlag { get; set; }
        public Nullable<System.DateTime> CNP_DeleteFlag { get; set; }
    }
}
