//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBREPORTMOBILEAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Target
    {
        public string Target_ID { get; set; }
        public string Target_Name { get; set; }
        public string Us_id { get; set; }
        public string Shop_id { get; set; }
        public string Target_Group { get; set; }
        public Nullable<int> Target_Value { get; set; }
        public Nullable<System.DateTime> Target_DayStart { get; set; }
        public Nullable<System.DateTime> Target_DayEnd { get; set; }
        public Nullable<System.DateTime> Target_SyncFlag { get; set; }
        public Nullable<System.DateTime> Target_DeleteFlag { get; set; }
    }
}
