//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBREPORTMOBILEAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DTCTltmrange
    {
        public string ltm_id { get; set; }
        public string ltm_name { get; set; }
        public string ltm_detail { get; set; }
        public Nullable<int> ltm_status { get; set; }
        public Nullable<System.DateTime> ltm_SyncFlag { get; set; }
        public Nullable<System.DateTime> ltm_DeleteFlag { get; set; }
    }
}
