//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBREPORTMOBILEAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_user
    {
        public string Us_id { get; set; }
        public string Us_name { get; set; }
        public string Us_username { get; set; }
        public string Us_password { get; set; }
        public string Us_Role { get; set; }
        public string Us_SupGroup { get; set; }
        public string Us_text1 { get; set; }
        public string Us_text2 { get; set; }
        public string Us_text3 { get; set; }
        public string Us_text4 { get; set; }
        public string Us_text5 { get; set; }
        public string Us_text6 { get; set; }
        public string Us_text7 { get; set; }
        public Nullable<double> Us_float1 { get; set; }
        public Nullable<double> Us_float2 { get; set; }
        public Nullable<double> Us_float3 { get; set; }
        public Nullable<double> Us_float4 { get; set; }
        public Nullable<System.DateTime> Us_datetime1 { get; set; }
        public Nullable<System.DateTime> Us_datetime2 { get; set; }
        public Nullable<System.DateTime> Us_datetime3 { get; set; }
        public Nullable<System.DateTime> Us_datetime4 { get; set; }
        public Nullable<System.DateTime> Us_datetime5 { get; set; }
        public Nullable<bool> Us_bit { get; set; }
        public Nullable<System.DateTime> Us_deleteflag { get; set; }
        public Nullable<System.DateTime> Us_SyncFlag { get; set; }
        public string US_TypeKho { get; set; }
    }
}
