//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBREPORTMOBILEAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_DOIQUA
    {
        public double DMQT_Barcode { get; set; }
        public string DMQT_Name { get; set; }
        public string DMQT_Detail { get; set; }
        public Nullable<bool> DMQT_Status { get; set; }
        public Nullable<System.DateTime> DMQT_SyncFlag { get; set; }
        public Nullable<System.DateTime> DMQT_DeleteFlag { get; set; }
        public string CTDQ_ID { get; set; }
        public string CTDQ_Name { get; set; }
        public string CTDQ_Detail { get; set; }
        public string CTDQ_APPLYROLE { get; set; }
        public Nullable<System.DateTime> CTDQ_DateBatDau { get; set; }
        public Nullable<System.DateTime> CTDQ_DateKetThuc { get; set; }
        public Nullable<System.DateTime> CTDQ_SyncFlag { get; set; }
        public Nullable<System.DateTime> CTDQ_DeleteFlag { get; set; }
        public Nullable<System.DateTime> DoiQua_DeleteFlag { get; set; }
        public Nullable<System.DateTime> DoiQua_SyncFlag { get; set; }
        public Nullable<int> DoiQua_Value { get; set; }
        public Nullable<System.DateTime> Bill_date { get; set; }
        public Nullable<System.DateTime> Bill_deleteFlag { get; set; }
        public string Bill_id { get; set; }
        public string Bill_ImageKH { get; set; }
        public string Bill_SDTKH { get; set; }
        public Nullable<System.DateTime> Bill_SyncFlag { get; set; }
        public string Bill_TenKH { get; set; }
        public string Shop_id { get; set; }
        public string Us_id { get; set; }
    }
}
