//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBREPORTMOBILEAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_KHO
    {
        public string Shop_id { get; set; }
        public string Shop_name { get; set; }
        public string Shop_detail { get; set; }
        public string Shop_npp { get; set; }
        public string Shop_nppcode { get; set; }
        public string Shop_Ngcode { get; set; }
        public string Shop_LoaiCHCurrent { get; set; }
        public string Shop_LoaiCHFuture { get; set; }
        public Nullable<double> Shop_latidue { get; set; }
        public Nullable<double> Shop_Longtidue { get; set; }
        public string Shop_phone { get; set; }
        public string Shop_Sup { get; set; }
        public string Shop_GroupPrice { get; set; }
        public string Shop_text2 { get; set; }
        public string Shop_text3 { get; set; }
        public string Shop_text4 { get; set; }
        public Nullable<double> Shop_float1 { get; set; }
        public Nullable<double> Shop_float2 { get; set; }
        public Nullable<double> Shop_float3 { get; set; }
        public Nullable<double> Shop_float4 { get; set; }
        public Nullable<bool> Shop_bit { get; set; }
        public Nullable<System.DateTime> Shop_datetime1 { get; set; }
        public Nullable<System.DateTime> Shop_datetime2 { get; set; }
        public Nullable<System.DateTime> Shop_datetime3 { get; set; }
        public Nullable<System.DateTime> Shop_datetime4 { get; set; }
        public Nullable<System.DateTime> Shop_deleteflag { get; set; }
        public Nullable<System.DateTime> Shop_SyncFlag { get; set; }
        public double DMQT_Barcode { get; set; }
        public string DMQT_Name { get; set; }
        public string DMQT_Detail { get; set; }
        public Nullable<bool> DMQT_Status { get; set; }
        public Nullable<System.DateTime> DMQT_SyncFlag { get; set; }
        public Nullable<System.DateTime> DMQT_DeleteFlag { get; set; }
        public Nullable<int> SL { get; set; }
    }
}
