//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBREPORTMOBILEAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_Supchamdiem
    {
        public string Us_id { get; set; }
        public string Us_name { get; set; }
        public string Us_username { get; set; }
        public string Us_password { get; set; }
        public string Us_Role { get; set; }
        public string Us_SupGroup { get; set; }
        public string Us_text1 { get; set; }
        public string Us_text2 { get; set; }
        public string Us_text3 { get; set; }
        public string Us_text4 { get; set; }
        public string Us_text5 { get; set; }
        public string Us_text6 { get; set; }
        public string Us_text7 { get; set; }
        public Nullable<double> Us_float1 { get; set; }
        public Nullable<double> Us_float2 { get; set; }
        public Nullable<double> Us_float3 { get; set; }
        public Nullable<double> Us_float4 { get; set; }
        public Nullable<System.DateTime> Us_datetime1 { get; set; }
        public Nullable<System.DateTime> Us_datetime2 { get; set; }
        public Nullable<System.DateTime> Us_datetime3 { get; set; }
        public Nullable<System.DateTime> Us_datetime4 { get; set; }
        public Nullable<System.DateTime> Us_datetime5 { get; set; }
        public Nullable<bool> Us_bit { get; set; }
        public Nullable<System.DateTime> Us_deleteflag { get; set; }
        public Nullable<System.DateTime> Us_SyncFlag { get; set; }
        public string US_TypeKho { get; set; }
        public string Shop_id { get; set; }
        public string Shop_name { get; set; }
        public string Shop_detail { get; set; }
        public string Shop_npp { get; set; }
        public string Shop_nppcode { get; set; }
        public string Shop_Ngcode { get; set; }
        public string Shop_LoaiCHCurrent { get; set; }
        public string Shop_LoaiCHFuture { get; set; }
        public Nullable<double> Shop_latidue { get; set; }
        public Nullable<double> Shop_Longtidue { get; set; }
        public string Shop_phone { get; set; }
        public string Shop_Sup { get; set; }
        public string Shop_GroupPrice { get; set; }
        public string Shop_text2 { get; set; }
        public string Shop_text3 { get; set; }
        public string Shop_text4 { get; set; }
        public Nullable<double> Shop_float1 { get; set; }
        public Nullable<double> Shop_float2 { get; set; }
        public Nullable<double> Shop_float3 { get; set; }
        public Nullable<double> Shop_float4 { get; set; }
        public Nullable<bool> Shop_bit { get; set; }
        public Nullable<System.DateTime> Shop_datetime1 { get; set; }
        public Nullable<System.DateTime> Shop_datetime2 { get; set; }
        public Nullable<System.DateTime> Shop_datetime3 { get; set; }
        public Nullable<System.DateTime> Shop_datetime4 { get; set; }
        public Nullable<System.DateTime> Shop_deleteflag { get; set; }
        public Nullable<System.DateTime> Shop_SyncFlag { get; set; }
        public string TieuChiCD_id { get; set; }
        public string TieuChiCD_Name { get; set; }
        public Nullable<int> TieuChiCD_Min { get; set; }
        public Nullable<int> TieuChiCD_Max { get; set; }
        public string TieuChiCD_Group { get; set; }
        public string TieuChiCD_text1 { get; set; }
        public string TieuChiCD_text2 { get; set; }
        public string TieuChiCD_text3 { get; set; }
        public string TieuChiCD_text4 { get; set; }
        public Nullable<double> TieuChiCD_float1 { get; set; }
        public Nullable<double> TieuChiCD_float2 { get; set; }
        public Nullable<double> TieuChiCD_float3 { get; set; }
        public Nullable<double> TieuChiCD_float4 { get; set; }
        public Nullable<bool> TieuChiCD_bit { get; set; }
        public Nullable<System.DateTime> TieuChiCD_DeleteFlag { get; set; }
        public Nullable<System.DateTime> TieuChiCD_SyncFlag { get; set; }
        public Nullable<System.DateTime> SupChamDiem_DeleteFlag { get; set; }
        public string SupChamDiem_id { get; set; }
        public string SupChamDiem_Lannay { get; set; }
        public string SupChamDiem_LanToi { get; set; }
        public Nullable<System.DateTime> SupChamDiem_SyncFlag { get; set; }
        public Nullable<System.DateTime> SupChamDiem_TimeCD { get; set; }
        public string SupChamDiem_UserAccept { get; set; }
        public string SupChamDiem_UserNote { get; set; }
        public System.DateTime SupBigPlan_date { get; set; }
        public Nullable<System.DateTime> SupBigPlan_DeleteFlag { get; set; }
        public string SupBigPlan_GroupPlan { get; set; }
        public string SupBigPlan_id { get; set; }
        public string SupBigPlan_KeHoachLanToi { get; set; }
        public string SupBigPlan_NXkehoachLanNay { get; set; }
        public string SupBigPlan_SupName { get; set; }
        public string SupBigPlan_SupUsername { get; set; }
        public Nullable<System.DateTime> SupBigPlan_SyncFlag { get; set; }
        public Nullable<int> SupBigPlan_UserAccept { get; set; }
        public string SupBigPlan_UserNote { get; set; }
        public Nullable<System.DateTime> ChitietSupChamDiem_DeleteFlag { get; set; }
        public string ChitietSupChamDiem_ID { get; set; }
        public Nullable<System.DateTime> ChitietSupChamDiem_SyncFlag { get; set; }
        public Nullable<int> ChitietSupChamDiem_value { get; set; }
    }
}
