//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIFORMOBILEAPPWORKING.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DTCTcrmrange
    {
        public string crm_id { get; set; }
        public string crm_name { get; set; }
        public string crm_detail { get; set; }
        public Nullable<int> crm_status { get; set; }
        public Nullable<System.DateTime> crm_SyncFlag { get; set; }
        public Nullable<System.DateTime> crm_DeleteFlag { get; set; }
    }
}
