//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIFORMOBILEAPPWORKING.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SupChamDiem
    {
        public string SupChamDiem_id { get; set; }
        public string SupBigPlan_id { get; set; }
        public Nullable<System.DateTime> SupChamDiem_TimeCD { get; set; }
        public string SupChamDiem_UserAccept { get; set; }
        public string SupChamDiem_UserNote { get; set; }
        public Nullable<System.DateTime> SupChamDiem_DeleteFlag { get; set; }
        public Nullable<System.DateTime> SupChamDiem_SyncFlag { get; set; }
        public string SupChamDiem_Lannay { get; set; }
        public string SupChamDiem_LanToi { get; set; }
    }
}
