//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIFORMOBILEAPPWORKING.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DTCTformat
    {
        public string bf_id { get; set; }
        public string bf_name { get; set; }
        public string bf_details { get; set; }
        public Nullable<int> bf_status { get; set; }
        public Nullable<System.DateTime> bf_SyncFlag { get; set; }
        public Nullable<System.DateTime> bf_DeleteFlag { get; set; }
    }
}
