//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIFORMOBILEAPPWORKING.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CaLamViecDetail
    {
        public string CaLamViecDetail_id { get; set; }
        public string CaLamViecDetail_Name { get; set; }
        public Nullable<System.TimeSpan> CaLamViecDetail_TGBD { get; set; }
        public Nullable<System.TimeSpan> CaLamViecDetail_TGKT { get; set; }
        public Nullable<double> CaLamViecDetail_CHAMCONG { get; set; }
        public Nullable<System.DateTime> CaLamViecDetail_DeleteFlag { get; set; }
        public Nullable<System.DateTime> CaLamViecDetail_SyncFlag { get; set; }
    }
}
