//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIFORMOBILEAPPWORKING.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_doithucanhtranhdongian
    {
        public string DTCTIMAGE_ID { get; set; }
        public Nullable<System.DateTime> DTCTIMAGE_Date { get; set; }
        public string US_ID { get; set; }
        public string Shop_ID { get; set; }
        public string DTCTIMAGE_Note { get; set; }
        public Nullable<System.DateTime> DTCTIMAGE_SyncFlag { get; set; }
        public Nullable<System.DateTime> DTCTIMAGE_DeleteFlag { get; set; }
        public Nullable<System.DateTime> DTCTIMAGED_DeleteFlag { get; set; }
        public string DTCTIMAGED_ID { get; set; }
        public string DTCTIMAGED_Image { get; set; }
        public string DTCTIMAGED_ImagePublish { get; set; }
        public string DTCTIMAGED_Note { get; set; }
        public Nullable<System.DateTime> DTCTIMAGED_SyncFlag { get; set; }
    }
}
