//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIFORMOBILEAPPWORKING.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_UsercheckInout
    {
        public string Us_id { get; set; }
        public string Us_name { get; set; }
        public string Us_username { get; set; }
        public string Us_password { get; set; }
        public string Us_Role { get; set; }
        public string Us_SupGroup { get; set; }
        public string Us_text1 { get; set; }
        public string Us_text2 { get; set; }
        public string Us_text3 { get; set; }
        public string Us_text4 { get; set; }
        public string Us_text5 { get; set; }
        public string Us_text6 { get; set; }
        public string Us_text7 { get; set; }
        public Nullable<double> Us_float1 { get; set; }
        public Nullable<double> Us_float2 { get; set; }
        public Nullable<double> Us_float3 { get; set; }
        public Nullable<double> Us_float4 { get; set; }
        public Nullable<System.DateTime> Us_datetime1 { get; set; }
        public Nullable<System.DateTime> Us_datetime2 { get; set; }
        public Nullable<System.DateTime> Us_datetime3 { get; set; }
        public Nullable<System.DateTime> Us_datetime4 { get; set; }
        public Nullable<System.DateTime> Us_datetime5 { get; set; }
        public Nullable<bool> Us_bit { get; set; }
        public Nullable<System.DateTime> Us_deleteflag { get; set; }
        public Nullable<System.DateTime> Us_SyncFlag { get; set; }
        public string US_TypeKho { get; set; }
        public string Shop_id { get; set; }
        public string Shop_name { get; set; }
        public string Shop_detail { get; set; }
        public string Shop_npp { get; set; }
        public string Shop_nppcode { get; set; }
        public string Shop_Ngcode { get; set; }
        public string Shop_LoaiCHCurrent { get; set; }
        public string Shop_LoaiCHFuture { get; set; }
        public Nullable<double> Shop_latidue { get; set; }
        public Nullable<double> Shop_Longtidue { get; set; }
        public string Shop_phone { get; set; }
        public string Shop_Sup { get; set; }
        public string Shop_GroupPrice { get; set; }
        public string Shop_text2 { get; set; }
        public string Shop_text3 { get; set; }
        public string Shop_text4 { get; set; }
        public Nullable<double> Shop_float1 { get; set; }
        public Nullable<double> Shop_float2 { get; set; }
        public Nullable<double> Shop_float3 { get; set; }
        public Nullable<double> Shop_float4 { get; set; }
        public Nullable<bool> Shop_bit { get; set; }
        public Nullable<System.DateTime> Shop_datetime1 { get; set; }
        public Nullable<System.DateTime> Shop_datetime2 { get; set; }
        public Nullable<System.DateTime> Shop_datetime3 { get; set; }
        public Nullable<System.DateTime> Shop_datetime4 { get; set; }
        public Nullable<System.DateTime> Shop_deleteflag { get; set; }
        public Nullable<System.DateTime> Shop_SyncFlag { get; set; }
        public System.DateTime Bigplan_date { get; set; }
        public Nullable<System.DateTime> Bigplan_deleteFlag { get; set; }
        public string Bigplan_id { get; set; }
        public Nullable<System.DateTime> BigPlan_SyncFlag { get; set; }
        public string CaLamViecDetail_id { get; set; }
        public Nullable<int> UserCheckInOut_AdminCheck { get; set; }
        public string UserCheckInOut_AdminNote { get; set; }
        public Nullable<double> UserCheckInOut_Count { get; set; }
        public System.DateTime UserCheckInOut_date { get; set; }
        public Nullable<System.DateTime> UserCheckInOut_DeleteFlag { get; set; }
        public string UserCheckInOut_ID { get; set; }
        public string UserCheckInOut_ImageCI { get; set; }
        public string UserCheckInOut_ImageCO { get; set; }
        public Nullable<double> UserCheckInOut_LatidueCI { get; set; }
        public Nullable<double> UserCheckInOut_LatidueCO { get; set; }
        public Nullable<double> UserCheckInOut_LongtidueCI { get; set; }
        public Nullable<double> UserCheckInOut_LongtidueCO { get; set; }
        public Nullable<System.DateTime> UserCheckInOut_SyncFlag { get; set; }
        public Nullable<System.DateTime> UserCheckInOut_TimeCI { get; set; }
        public Nullable<System.DateTime> UserCheckInOut_TimeCO { get; set; }
        public string UserCheckInOut_UserNote { get; set; }
        public string UserCheckInOut_ImageCI1 { get; set; }
        public string UserCheckInOut_ImageCO1 { get; set; }
        public string UserCheckInOut_ImageCI2 { get; set; }
        public string UserCheckInOut_ImageCO2 { get; set; }
        public string UserCheckInOut_ImageCI3 { get; set; }
        public string UserCheckInOut_ImageCO3 { get; set; }
    }
}
