//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBREPORTMOBILEAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Kho
    {
        public string KHO_ID { get; set; }
        public string Shop_IDNguon { get; set; }
        public string KHO_ACTION { get; set; }
        public string Shop_IDDICH { get; set; }
        public Nullable<double> DMQT_Barcode { get; set; }
        public Nullable<int> KHO_SOLUONG { get; set; }
        public Nullable<System.DateTime> KHO_Time { get; set; }
        public Nullable<bool> KHO_ACCEPT { get; set; }
        public Nullable<System.DateTime> KHO_SyncFlag { get; set; }
        public Nullable<System.DateTime> KHO_DeleteFlag { get; set; }
        public string KHO_UsIDDich { get; set; }
        public string KHO_USNameDich { get; set; }
        public string KHO_UsIDNguon { get; set; }
        public string KHO_USNameNguon { get; set; }
    }
}
