//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBREPORTMOBILEAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SupBigPlan
    {
        public string SupBigPlan_id { get; set; }
        public string Us_id { get; set; }
        public string Shop_id { get; set; }
        public System.DateTime SupBigPlan_date { get; set; }
        public string SupBigPlan_NXkehoachLanNay { get; set; }
        public string SupBigPlan_KeHoachLanToi { get; set; }
        public string SupBigPlan_GroupPlan { get; set; }
        public Nullable<int> SupBigPlan_UserAccept { get; set; }
        public string SupBigPlan_UserNote { get; set; }
        public Nullable<System.DateTime> SupBigPlan_DeleteFlag { get; set; }
        public Nullable<System.DateTime> SupBigPlan_SyncFlag { get; set; }
        public string SupBigPlan_SupName { get; set; }
        public string SupBigPlan_SupUsername { get; set; }
    }
}
