//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBREPORTMOBILEAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_menu
    {
        public int Menu_id { get; set; }
        public string Menu_Name { get; set; }
        public string Menu_code { get; set; }
        public string Menu_Role { get; set; }
        public Nullable<System.DateTime> Menu_DeleteFlag { get; set; }
        public Nullable<System.DateTime> Menu_SyncFlag { get; set; }
        public Nullable<int> Menu_Status { get; set; }
    }
}
