//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBREPORTMOBILEAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_RulesChuongTrinhDoiQua
    {
        public string CTDQ_ID { get; set; }
        public string RCTDQ_ID { get; set; }
        public Nullable<int> RCTDQ_Value { get; set; }
        public string RCTDQ_And { get; set; }
        public string RCTDQ_Or { get; set; }
        public Nullable<System.DateTime> RCTDQ_SyncFlag { get; set; }
        public Nullable<System.DateTime> RCTDQ_Delete { get; set; }
        public string RCTDQ_NhomNganhHang { get; set; }
        public string RCTDQ_NganhHang { get; set; }
        public string RCTDQ_NhanHang { get; set; }
        public Nullable<int> RCTDQ_ValueNhomNganhNhanHang { get; set; }
        public Nullable<int> RCTDQ_ValueNganhHang { get; set; }
        public Nullable<int> RCTDQ_ValueNhanHang { get; set; }
        public string RCTDQ_SanPham { get; set; }
        public Nullable<int> RCTDQ_ValueSanPham { get; set; }
    }
}
