//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBREPORTMOBILEAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_ReportDQN
    {
        public int RP_ID { get; set; }
        public string PG_Phone { get; set; }
        public string PG_Name { get; set; }
        public string Store_code { get; set; }
        public string Store_Name { get; set; }
        public string Name_KH { get; set; }
        public string Phone { get; set; }
        public string Gender { get; set; }
        public Nullable<double> Total_Bill { get; set; }
        public Nullable<double> Total_Bill_ULV { get; set; }
        public Nullable<int> Num_voucher { get; set; }
        public Nullable<bool> IsDove { get; set; }
        public Nullable<System.DateTime> Created_At { get; set; }
    }
}
