//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIFORMOBILEAPPWORKING.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ChuongTrinhDoiQua
    {
        public string CTDQ_ID { get; set; }
        public string CTDQ_Name { get; set; }
        public string CTDQ_Detail { get; set; }
        public string CTDQ_APPLYROLE { get; set; }
        public Nullable<System.DateTime> CTDQ_DateBatDau { get; set; }
        public Nullable<System.DateTime> CTDQ_DateKetThuc { get; set; }
        public Nullable<System.DateTime> CTDQ_SyncFlag { get; set; }
        public Nullable<System.DateTime> CTDQ_DeleteFlag { get; set; }
    }
}
