//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIFORMOBILEAPPWORKING.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_BillCNKDetail
    {
        public string DBCNK_ID { get; set; }
        public string BCNK_ID { get; set; }
        public Nullable<double> DMQT_Barcode { get; set; }
        public string Us_IDnhan { get; set; }
        public string Us_NameNhan { get; set; }
        public Nullable<int> DBCNK_SoluongChuyen { get; set; }
        public Nullable<int> DBCNK_SoluongNhan { get; set; }
        public Nullable<bool> DBCNK_XacNhanNhan { get; set; }
        public Nullable<bool> DBCNK_XacNhanChuyen { get; set; }
        public string DBCNK_NoteXacNhanNhan { get; set; }
        public string DBCNK_NoteXacNhanChuyen { get; set; }
        public Nullable<System.DateTime> DBCNK_SyncFlag { get; set; }
        public Nullable<System.DateTime> DBCNK_DeleteFlag { get; set; }
    }
}
