//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIFORMOBILEAPPWORKING.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_NhanHang
    {
        public string NhanH_ID { get; set; }
        public string NhanH_Name { get; set; }
        public Nullable<bool> NhanH_Status { get; set; }
        public Nullable<System.DateTime> NhanH_SyncFlag { get; set; }
        public Nullable<System.DateTime> NhanH_DeleteFlag { get; set; }
    }
}
