//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIFORMOBILEAPPWORKING.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_ChitietDonNhapHang
    {
        public string CTDNH_ID { get; set; }
        public string DNH_ID { get; set; }
        public Nullable<double> sku_id { get; set; }
        public Nullable<double> CTDNH_Soluong { get; set; }
        public Nullable<System.DateTime> CTDNH_Date { get; set; }
        public Nullable<System.DateTime> CTDNH_SyncFlag { get; set; }
        public Nullable<System.DateTime> CTDNH_DeleteFlag { get; set; }
    }
}
