//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIFORMOBILEAPPWORKING.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_KhoXe
    {
        public string KX_ID { get; set; }
        public string KX_Name { get; set; }
        public string KX_Adress { get; set; }
        public string KX_Phone { get; set; }
        public string KX_TenNguoiGiuKho { get; set; }
        public string KX_UserQuanLy { get; set; }
        public string KX_Type { get; set; }
        public Nullable<System.DateTime> KX_SyncFlag { get; set; }
        public Nullable<System.DateTime> KX_DeleteFlag { get; set; }
    }
}
