//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIFORMOBILEAPPWORKING.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_sku
    {
        public double sku_barcode { get; set; }
        public string sku_name { get; set; }
        public string sku_detail { get; set; }
        public string sku_txtname { get; set; }
        public Nullable<double> sku_txtPrice { get; set; }
        public string Target_Group { get; set; }
        public string sku_text1 { get; set; }
        public string sku_text2 { get; set; }
        public string sku_text3 { get; set; }
        public string sku_text4 { get; set; }
        public string sku_text5 { get; set; }
        public Nullable<double> sku_float1 { get; set; }
        public Nullable<double> sku_float2 { get; set; }
        public Nullable<double> sku_float3 { get; set; }
        public Nullable<double> sku_float4 { get; set; }
        public Nullable<double> sku_float5 { get; set; }
        public Nullable<double> sku_float6 { get; set; }
        public Nullable<System.DateTime> sku_datetime1 { get; set; }
        public Nullable<System.DateTime> sku_datetime2 { get; set; }
        public Nullable<System.DateTime> sku_datetime3 { get; set; }
        public Nullable<System.DateTime> sku_datetime4 { get; set; }
        public Nullable<bool> sku_bit { get; set; }
        public Nullable<System.DateTime> sku_deleteflag { get; set; }
        public Nullable<System.DateTime> sku_SyncFlag { get; set; }
    }
}
