//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIFORMOBILEAPPWORKING.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_KhoChuyenNhan
    {
        public string CNK_ID { get; set; }
        public string CNK_TypeChuyen { get; set; }
        public string CNK_TypeNhan { get; set; }
        public string CNK_IDChuyen { get; set; }
        public string CNK_NameChuyen { get; set; }
        public string CNK_IDNhan { get; set; }
        public string CNK_NameNhan { get; set; }
        public string BCNK_ID { get; set; }
        public Nullable<System.DateTime> CNK_SyncFlag { get; set; }
        public Nullable<System.DateTime> CNK_DeleteFlag { get; set; }
    }
}
