//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIFORMOBILEAPPWORKING.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_NganhHang
    {
        public string NH_ID { get; set; }
        public string NH_Name { get; set; }
        public Nullable<bool> NH_Status { get; set; }
        public Nullable<System.DateTime> NH_SyncFlag { get; set; }
        public Nullable<System.DateTime> NH_DeleteFlag { get; set; }
    }
}
