//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIFORMOBILEAPPWORKING.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DTCTonpostoffpost
    {
        public string ofpost_id { get; set; }
        public string ofpost_name { get; set; }
        public string ofpost_detail { get; set; }
        public Nullable<int> ofpost_status { get; set; }
        public Nullable<System.DateTime> ofpost_SyncFlag { get; set; }
        public Nullable<System.DateTime> ofpost_DeleteFlag { get; set; }
    }
}
