//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIFORMOBILEAPPWORKING.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_BillChuyenNhanKho
    {
        public string BCNK_ID { get; set; }
        public string Us_IDChuyen { get; set; }
        public string Us_NameChuyen { get; set; }
        public Nullable<System.DateTime> BCNK_Time { get; set; }
        public Nullable<System.DateTime> BCNK_SyncFlag { get; set; }
        public Nullable<System.DateTime> BCNK_DeleteFlag { get; set; }
    }
}
