//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIFORMOBILEAPPWORKING.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DoiQua
    {
        public string DoiQua_ID { get; set; }
        public string Bill_id { get; set; }
        public string RCTDQ_ID { get; set; }
        public double DMQT_Barcode { get; set; }
        public Nullable<int> DoiQua_Value { get; set; }
        public Nullable<System.DateTime> DoiQua_SyncFlag { get; set; }
        public Nullable<System.DateTime> DoiQua_DeleteFlag { get; set; }
    }
}
