//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIFORMOBILEAPPWORKING.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_UserCheckInOut
    {
        public string UserCheckInOut_ID { get; set; }
        public string Bigplan_id { get; set; }
        public System.DateTime UserCheckInOut_date { get; set; }
        public string UserCheckInOut_ImageCI { get; set; }
        public string UserCheckInOut_ImageCO { get; set; }
        public Nullable<System.DateTime> UserCheckInOut_TimeCI { get; set; }
        public Nullable<System.DateTime> UserCheckInOut_TimeCO { get; set; }
        public Nullable<double> UserCheckInOut_LatidueCI { get; set; }
        public Nullable<double> UserCheckInOut_LongtidueCI { get; set; }
        public Nullable<double> UserCheckInOut_LatidueCO { get; set; }
        public Nullable<double> UserCheckInOut_LongtidueCO { get; set; }
        public Nullable<int> UserCheckInOut_AdminCheck { get; set; }
        public string UserCheckInOut_AdminNote { get; set; }
        public string UserCheckInOut_UserNote { get; set; }
        public Nullable<double> UserCheckInOut_Count { get; set; }
        public Nullable<System.DateTime> UserCheckInOut_DeleteFlag { get; set; }
        public Nullable<System.DateTime> UserCheckInOut_SyncFlag { get; set; }
        public string UserCheckInOut_ImageCI1 { get; set; }
        public string UserCheckInOut_ImageCI2 { get; set; }
        public string UserCheckInOut_ImageCI3 { get; set; }
        public string UserCheckInOut_ImageCO1 { get; set; }
        public string UserCheckInOut_ImageCO2 { get; set; }
        public string UserCheckInOut_ImageCO3 { get; set; }
    }
}
