//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIFORMOBILEAPPWORKING.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DTCTffrange
    {
        public string ff_id { get; set; }
        public string ff_name { get; set; }
        public string ff_detail { get; set; }
        public Nullable<int> ff_status { get; set; }
        public Nullable<System.DateTime> ff_SyncFlag { get; set; }
        public Nullable<System.DateTime> ff_DeleteFlag { get; set; }
    }
}
