//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBREPORTMOBILEAPP.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DBMOBILEAPPMAEntities : DbContext
    {
        public DBMOBILEAPPMAEntities()
            : base("name=DBMOBILEAPPMAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_BaoCaoHinhAnh> tbl_BaoCaoHinhAnh { get; set; }
        public virtual DbSet<tbl_bigplan> tbl_bigplan { get; set; }
        public virtual DbSet<tbl_bill> tbl_bill { get; set; }
        public virtual DbSet<Tbl_BillCNKDetail> Tbl_BillCNKDetail { get; set; }
        public virtual DbSet<Tbl_BillChuyenNhanKho> Tbl_BillChuyenNhanKho { get; set; }
        public virtual DbSet<tbl_billDetail> tbl_billDetail { get; set; }
        public virtual DbSet<tbl_CaLamViecDetail> tbl_CaLamViecDetail { get; set; }
        public virtual DbSet<tbl_chitietDondathang> tbl_chitietDondathang { get; set; }
        public virtual DbSet<Tbl_ChitietDonNhapHang> Tbl_ChitietDonNhapHang { get; set; }
        public virtual DbSet<tbl_ChitietSupChamDiem> tbl_ChitietSupChamDiem { get; set; }
        public virtual DbSet<tbl_chucnangphu> tbl_chucnangphu { get; set; }
        public virtual DbSet<tbl_ChuongTrinhDoiQua> tbl_ChuongTrinhDoiQua { get; set; }
        public virtual DbSet<tbl_DanhMucQuaTang> tbl_DanhMucQuaTang { get; set; }
        public virtual DbSet<tbl_DetailBaoCaoHinhAnh> tbl_DetailBaoCaoHinhAnh { get; set; }
        public virtual DbSet<tbl_DMQT_CTDQ> tbl_DMQT_CTDQ { get; set; }
        public virtual DbSet<tbl_DoiQua> tbl_DoiQua { get; set; }
        public virtual DbSet<tbl_doithucanhtranh> tbl_doithucanhtranh { get; set; }
        public virtual DbSet<Tbl_DoithucanhtranhIMAGE> Tbl_DoithucanhtranhIMAGE { get; set; }
        public virtual DbSet<Tbl_DoithucanhtranhIMAGEDetail> Tbl_DoithucanhtranhIMAGEDetail { get; set; }
        public virtual DbSet<tbl_Dondathang> tbl_Dondathang { get; set; }
        public virtual DbSet<Tbl_DonNhapHang> Tbl_DonNhapHang { get; set; }
        public virtual DbSet<tbl_DTCTBrand> tbl_DTCTBrand { get; set; }
        public virtual DbSet<tbl_DTCTcrmrange> tbl_DTCTcrmrange { get; set; }
        public virtual DbSet<tbl_DTCTCty> tbl_DTCTCty { get; set; }
        public virtual DbSet<tbl_DTCTffrange> tbl_DTCTffrange { get; set; }
        public virtual DbSet<tbl_DTCTformat> tbl_DTCTformat { get; set; }
        public virtual DbSet<tbl_DTCTltmrange> tbl_DTCTltmrange { get; set; }
        public virtual DbSet<tbl_DTCTonpostoffpost> tbl_DTCTonpostoffpost { get; set; }
        public virtual DbSet<tbl_DTCTtype> tbl_DTCTtype { get; set; }
        public virtual DbSet<tbl_DTCTVARIANT> tbl_DTCTVARIANT { get; set; }
        public virtual DbSet<Tbl_HsSms> Tbl_HsSms { get; set; }
        public virtual DbSet<Tbl_ImageDonNhapHang> Tbl_ImageDonNhapHang { get; set; }
        public virtual DbSet<tbl_Kho> tbl_Kho { get; set; }
        public virtual DbSet<Tbl_KhoChiNhanh> Tbl_KhoChiNhanh { get; set; }
        public virtual DbSet<Tbl_KhoChuyenNhan> Tbl_KhoChuyenNhan { get; set; }
        public virtual DbSet<Tbl_KhoDoi> Tbl_KhoDoi { get; set; }
        public virtual DbSet<Tbl_KHOQUA> Tbl_KHOQUA { get; set; }
        public virtual DbSet<Tbl_KhoXe> Tbl_KhoXe { get; set; }
        public virtual DbSet<Tbl_KHtiepcan> Tbl_KHtiepcan { get; set; }
        public virtual DbSet<tbl_menu> tbl_menu { get; set; }
        public virtual DbSet<tbl_NganhHang> tbl_NganhHang { get; set; }
        public virtual DbSet<tbl_NhanHang> tbl_NhanHang { get; set; }
        public virtual DbSet<tbl_NhomNganhHang> tbl_NhomNganhHang { get; set; }
        public virtual DbSet<tbl_Price> tbl_Price { get; set; }
        public virtual DbSet<tbl_RulesChuongTrinhDoiQua> tbl_RulesChuongTrinhDoiQua { get; set; }
        public virtual DbSet<tbl_shop> tbl_shop { get; set; }
        public virtual DbSet<tbl_sku> tbl_sku { get; set; }
        public virtual DbSet<tbl_skutemp> tbl_skutemp { get; set; }
        public virtual DbSet<tbl_SupBigPlan> tbl_SupBigPlan { get; set; }
        public virtual DbSet<tbl_SupChamDiem> tbl_SupChamDiem { get; set; }
        public virtual DbSet<tbl_SupCheckIn> tbl_SupCheckIn { get; set; }
        public virtual DbSet<Tbl_SupName> Tbl_SupName { get; set; }
        public virtual DbSet<tbl_Target> tbl_Target { get; set; }
        public virtual DbSet<tbl_TieuChiBaoCaoHinhAnh> tbl_TieuChiBaoCaoHinhAnh { get; set; }
        public virtual DbSet<tbl_TieuChiChamDiem> tbl_TieuChiChamDiem { get; set; }
        public virtual DbSet<tbl_user> tbl_user { get; set; }
        public virtual DbSet<tbl_UserCheckInOut> tbl_UserCheckInOut { get; set; }
        public virtual DbSet<VW_banhang> VW_banhang { get; set; }
        public virtual DbSet<VW_BCHINHANH> VW_BCHINHANH { get; set; }
        public virtual DbSet<VW_Bigplan> VW_Bigplan { get; set; }
        public virtual DbSet<VW_DatHang> VW_DatHang { get; set; }
        public virtual DbSet<VW_DeXuatNhapHang> VW_DeXuatNhapHang { get; set; }
        public virtual DbSet<VW_DOIQUA> VW_DOIQUA { get; set; }
        public virtual DbSet<vw_doithucanhtranh> vw_doithucanhtranh { get; set; }
        public virtual DbSet<VW_DoithucanhtranhImage> VW_DoithucanhtranhImage { get; set; }
        public virtual DbSet<VW_KHO> VW_KHO { get; set; }
        public virtual DbSet<VW_NHAPHANG> VW_NHAPHANG { get; set; }
        public virtual DbSet<VW_ReportQua> VW_ReportQua { get; set; }
        public virtual DbSet<VW_SMSOTP> VW_SMSOTP { get; set; }
        public virtual DbSet<VW_Supchamdiem> VW_Supchamdiem { get; set; }
        public virtual DbSet<VW_SupCheckin> VW_SupCheckin { get; set; }
        public virtual DbSet<VW_SUPCHECKINOUT> VW_SUPCHECKINOUT { get; set; }
        public virtual DbSet<VW_UsercheckInout> VW_UsercheckInout { get; set; }
    
        [DbFunction("DBMOBILEAPPMAEntities", "splitstring")]
        public virtual IQueryable<splitstring_Result> splitstring(string stringToSplit)
        {
            var stringToSplitParameter = stringToSplit != null ?
                new ObjectParameter("stringToSplit", stringToSplit) :
                new ObjectParameter("stringToSplit", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<splitstring_Result>("[DBMOBILEAPPMAEntities].[splitstring](@stringToSplit)", stringToSplitParameter);
        }
    
        public virtual int sp_suabaocaokh(string khid, Nullable<int> tc, Nullable<int> tctc, Nullable<int> dt, string date)
        {
            var khidParameter = khid != null ?
                new ObjectParameter("khid", khid) :
                new ObjectParameter("khid", typeof(string));
    
            var tcParameter = tc.HasValue ?
                new ObjectParameter("tc", tc) :
                new ObjectParameter("tc", typeof(int));
    
            var tctcParameter = tctc.HasValue ?
                new ObjectParameter("tctc", tctc) :
                new ObjectParameter("tctc", typeof(int));
    
            var dtParameter = dt.HasValue ?
                new ObjectParameter("dt", dt) :
                new ObjectParameter("dt", typeof(int));
    
            var dateParameter = date != null ?
                new ObjectParameter("date", date) :
                new ObjectParameter("date", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_suabaocaokh", khidParameter, tcParameter, tctcParameter, dtParameter, dateParameter);
        }
    
        public virtual int Sp_Suabill(string billid, Nullable<System.DateTime> dt)
        {
            var billidParameter = billid != null ?
                new ObjectParameter("billid", billid) :
                new ObjectParameter("billid", typeof(string));
    
            var dtParameter = dt.HasValue ?
                new ObjectParameter("dt", dt) :
                new ObjectParameter("dt", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_Suabill", billidParameter, dtParameter);
        }
    
        public virtual int sp_thembaocaokh(string bigid, Nullable<int> tc, Nullable<int> tctc, Nullable<int> dt, string date)
        {
            var bigidParameter = bigid != null ?
                new ObjectParameter("bigid", bigid) :
                new ObjectParameter("bigid", typeof(string));
    
            var tcParameter = tc.HasValue ?
                new ObjectParameter("tc", tc) :
                new ObjectParameter("tc", typeof(int));
    
            var tctcParameter = tctc.HasValue ?
                new ObjectParameter("tctc", tctc) :
                new ObjectParameter("tctc", typeof(int));
    
            var dtParameter = dt.HasValue ?
                new ObjectParameter("dt", dt) :
                new ObjectParameter("dt", typeof(int));
    
            var dateParameter = date != null ?
                new ObjectParameter("date", date) :
                new ObjectParameter("date", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_thembaocaokh", bigidParameter, tcParameter, tctcParameter, dtParameter, dateParameter);
        }
    
        public virtual int Sp_ThemBill(string usid, string shopid, string billdate)
        {
            var usidParameter = usid != null ?
                new ObjectParameter("usid", usid) :
                new ObjectParameter("usid", typeof(string));
    
            var shopidParameter = shopid != null ?
                new ObjectParameter("shopid", shopid) :
                new ObjectParameter("shopid", typeof(string));
    
            var billdateParameter = billdate != null ?
                new ObjectParameter("billdate", billdate) :
                new ObjectParameter("billdate", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_ThemBill", usidParameter, shopidParameter, billdateParameter);
        }
    
        public virtual int Sp_Themdoiqua(string billid, Nullable<double> dmqtbarcode, string ctdqid, Nullable<int> sl)
        {
            var billidParameter = billid != null ?
                new ObjectParameter("billid", billid) :
                new ObjectParameter("billid", typeof(string));
    
            var dmqtbarcodeParameter = dmqtbarcode.HasValue ?
                new ObjectParameter("dmqtbarcode", dmqtbarcode) :
                new ObjectParameter("dmqtbarcode", typeof(double));
    
            var ctdqidParameter = ctdqid != null ?
                new ObjectParameter("ctdqid", ctdqid) :
                new ObjectParameter("ctdqid", typeof(string));
    
            var slParameter = sl.HasValue ?
                new ObjectParameter("sl", sl) :
                new ObjectParameter("sl", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_Themdoiqua", billidParameter, dmqtbarcodeParameter, ctdqidParameter, slParameter);
        }
    
        public virtual int Sp_ThemspBillDetail(string billid, Nullable<double> barcode, Nullable<int> sl, Nullable<double> dongia)
        {
            var billidParameter = billid != null ?
                new ObjectParameter("billid", billid) :
                new ObjectParameter("billid", typeof(string));
    
            var barcodeParameter = barcode.HasValue ?
                new ObjectParameter("barcode", barcode) :
                new ObjectParameter("barcode", typeof(double));
    
            var slParameter = sl.HasValue ?
                new ObjectParameter("sl", sl) :
                new ObjectParameter("sl", typeof(int));
    
            var dongiaParameter = dongia.HasValue ?
                new ObjectParameter("dongia", dongia) :
                new ObjectParameter("dongia", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_ThemspBillDetail", billidParameter, barcodeParameter, slParameter, dongiaParameter);
        }
    
        public virtual int Sp_xoabaocaokh(string id)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_xoabaocaokh", idParameter);
        }
    
        public virtual int Sp_xoabill(string billid)
        {
            var billidParameter = billid != null ?
                new ObjectParameter("billid", billid) :
                new ObjectParameter("billid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_xoabill", billidParameter);
        }
    
        public virtual int Sp_XoaDoiqua(string id)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_XoaDoiqua", idParameter);
        }
    
        public virtual int Sp_XoaspBillDetail(string billid, Nullable<double> barcode)
        {
            var billidParameter = billid != null ?
                new ObjectParameter("billid", billid) :
                new ObjectParameter("billid", typeof(string));
    
            var barcodeParameter = barcode.HasValue ?
                new ObjectParameter("barcode", barcode) :
                new ObjectParameter("barcode", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_XoaspBillDetail", billidParameter, barcodeParameter);
        }
    }
}
