//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBREPORTMOBILEAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_TieuChiChamDiem
    {
        public string TieuChiCD_id { get; set; }
        public string TieuChiCD_Name { get; set; }
        public Nullable<int> TieuChiCD_Min { get; set; }
        public Nullable<int> TieuChiCD_Max { get; set; }
        public string TieuChiCD_Group { get; set; }
        public string TieuChiCD_text1 { get; set; }
        public string TieuChiCD_text2 { get; set; }
        public string TieuChiCD_text3 { get; set; }
        public string TieuChiCD_text4 { get; set; }
        public Nullable<double> TieuChiCD_float1 { get; set; }
        public Nullable<double> TieuChiCD_float2 { get; set; }
        public Nullable<double> TieuChiCD_float3 { get; set; }
        public Nullable<double> TieuChiCD_float4 { get; set; }
        public Nullable<bool> TieuChiCD_bit { get; set; }
        public Nullable<System.DateTime> TieuChiCD_DeleteFlag { get; set; }
        public Nullable<System.DateTime> TieuChiCD_SyncFlag { get; set; }
    }
}
