//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBREPORTMOBILEAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_bigplan
    {
        public string Bigplan_id { get; set; }
        public string Us_id { get; set; }
        public string CaLamViecDetail_id { get; set; }
        public string Shop_id { get; set; }
        public System.DateTime Bigplan_date { get; set; }
        public Nullable<System.DateTime> Bigplan_deleteFlag { get; set; }
        public Nullable<System.DateTime> BigPlan_SyncFlag { get; set; }
    }
}
