//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBREPORTMOBILEAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_chitietDondathang
    {
        public string DDH_ID { get; set; }
        public double sku_barcode { get; set; }
        public Nullable<double> CTDDH_Soluong { get; set; }
        public Nullable<System.DateTime> CTDDH_SyncFlag { get; set; }
        public Nullable<System.DateTime> CTDDH_DeleteFlag { get; set; }
    }
}
