//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBREPORTMOBILEAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DMQT_CTDQ
    {
        public string DMCT_ID { get; set; }
        public Nullable<double> DMQT_Barcode { get; set; }
        public string CTDQ_ID { get; set; }
        public Nullable<bool> DMCT_Status { get; set; }
        public Nullable<System.DateTime> DMCT_SyncFlag { get; set; }
        public Nullable<System.DateTime> DMCT_DeleteFlag { get; set; }
    }
}
