//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBREPORTMOBILEAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DTCTBrand
    {
        public string Brand_id { get; set; }
        public string cty_id { get; set; }
        public string Brand_name { get; set; }
        public string Brand_details { get; set; }
        public Nullable<int> Brand_status { get; set; }
        public Nullable<System.DateTime> Brand_SyncFlag { get; set; }
        public Nullable<System.DateTime> Brand_DeleteFlag { get; set; }
    }
}
