//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBREPORTMOBILEAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DTCTtype
    {
        public string ty_id { get; set; }
        public string ty_name { get; set; }
        public string ty_details { get; set; }
        public Nullable<int> ty_status { get; set; }
        public Nullable<System.DateTime> ty_SyncFlag { get; set; }
        public Nullable<System.DateTime> ty_DeleteFlag { get; set; }
    }
}
