//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBREPORTMOBILEAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_TieuChiBaoCaoHinhAnh
    {
        public string TCBCHA_ID { get; set; }
        public string TCBCHA_Role { get; set; }
        public string TCBCHA_Name { get; set; }
        public Nullable<bool> TCBCHA_Status { get; set; }
        public Nullable<System.DateTime> TCBCHA_SyncFlag { get; set; }
        public Nullable<System.DateTime> TCBCHA_DeleteFlag { get; set; }
    }
}
